# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('week_number', models.IntegerField()),
                ('month_number', models.IntegerField()),
                ('attendance_mark', models.CharField(choices=[('FULL', 'FULL'), ('TARDY', 'TARDY'), ('ABSENT', 'ABSENT')], max_length=8)),
                ('hours_attended', models.IntegerField()),
                ('absent_excused', models.NullBooleanField()),
                ('tardy_reason', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hrs_per_mtg', models.IntegerField()),
                ('mtgs_per_week', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHproto.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('student_id_num', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('grad_year', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roster',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CHproto.Student'),
        ),
        migrations.AddField(
            model_name='roster',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CHproto.Roster'),
        ),
    ]
