# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
