# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0007_auto_20170515_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
