# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHproto', '0008_remove_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id_num',
            field=models.IntegerField(),
        ),
    ]
